POST http://localhost:5120/api/tasks/createtask
Content-Type: application/json

{
    "title": "Task 2",
    "description": "Description 1",
    "status": "To Do",
    "priority": "High",
    "dueDate": "2026-12-31",
    "assignedTo": { "username": "Tommy", "userID": "002" }
}

###

GET http://localhost:5120/api/tasks/getalltasks
Accept: application/json

###

GET http://localhost:5120/api/tasks/gettaskbyid?taskId=Task%202
Accept: application/json

###

GET http://localhost:5120/api/tasks/gettaskbyassignedto?assignedTo=Tommy
Accept: application/json

###

PUT http://localhost:5120/api/tasks/updatetaskstatus?taskId=Task%202&newStatus=Done
Accept: application/json

###

DELETE http://localhost:5120/api/tasks/deletetask?taskId=Task%202
Accept: application/json

###

POST http://localhost:5120/api/users/createUser
Content-Type: application/json

{
    "username": "Alice",
    "userID": "001"
}

###

GET http://localhost:5120/api/users/getAllUsers
Accept: application/json
